# Machine Learning Lab 6

Classification and group coding exercise.

## Imports

In [1]:
# Data and Datasets
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine

# Validation methods
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

# Metrics
from sklearn import metrics
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score

# Classifiers
from sklearn.neighbors import KNeighborsClassifier
from classifiers import k_nearest_neighbour # the K-NN python file in the 'classifiers' folder
from classifiers import random_classifier # the Random Classifier python file in the 'classifiers' folder

# Plotting & utils
import pprint
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Loading dataset (from sklearn, not from file)
dataset = load_iris()
X = dataset.data
y = dataset.target

## Random Classifier

In [3]:
# Splitting dataset for hold-out validation
X_train, X_test, y_train, y_test = train_test_split(X, # feature matrix
                                                    y, # label vector
                                                    test_size=0.2, # 20% test / 80% traing
                                                    random_state=1, # fixed random seed
                                                    stratify=y # split dataset proportional to classes
                                                   )

# Instantiating model
model = random_classifier.RandomClassifier()

# Training model
model = model.fit(X_train, y_train)

# Testing model
y_pred = model.predict(X_test)

# Printing out confusion matrix and accuracy
print(metrics.confusion_matrix(y_test, y_pred))
print("\nAccuracy (Testing):  %0.2f " % (metrics.accuracy_score(y_test, y_pred)))

[[3 3 4]
 [3 3 4]
 [2 2 6]]

Accuracy (Testing):  0.40 


## Bespoke K-NN

In [4]:
from classifiers import k_nearest_neighbour

# Instantiating model
model = k_nearest_neighbour.KNNClassifier(5)

# Training model
model = model.fit(X_train, y_train)

# Testing model
y_pred = model.predict(X_test)

# Printing out confusion matrix and accuracy
print(metrics.confusion_matrix(y_test, y_pred))
print("\nAccuracy (Testing):  %0.2f " % (metrics.accuracy_score(y_test, y_pred)))

Initialised K-NN
k = 5
Training...
Testing...
[[9 1 0]
 [2 4 4]
 [1 4 5]]

Accuracy (Testing):  0.60 


## Evaluation

Lab tasks on hold-out and cross-validation, etc.